//! Autogenerated weights for pallet_multi_coin
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `substrate-node`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/solochain-template-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_multi_coin
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output
// pallets/multi-coin/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_multi_coin.
pub trait WeightInfo {
	fn create_coin() -> Weight;
	fn transfer() -> Weight;
	fn mint() -> Weight;
	fn burn() -> Weight;
	fn transfer_ownership() -> Weight;
	fn set_mint_permission() -> Weight;
	fn set_metadata() -> Weight;
	fn set_fee_config() -> Weight; // New
}

/// Weights for pallet_multi_coin using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: MultiCoin CoinMetadata (r:1 w:1)
	/// Proof: MultiCoin CoinMetadata (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	/// Storage: MultiCoin SymbolToId (r:1 w:1)
	/// Proof: MultiCoin SymbolToId (max_values: None, max_size: Some(256), added: 2731, mode: MaxEncodedLen)
	/// Storage: MultiCoin NextCoinId (r:1 w:1)
	/// Proof: MultiCoin NextCoinId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: MultiCoin TotalSupply (r:0 w:1)
	/// Proof: MultiCoin TotalSupply (max_values: None, max_size: Some(20), added: 2495, mode: MaxEncodedLen)
	/// Storage: MultiCoin Balances (r:0 w:1)
	/// Proof: MultiCoin Balances (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: MultiCoin MintPermissions (r:0 w:1)
	/// Proof: MultiCoin MintPermissions (max_values: None, max_size: Some(37), added: 2512, mode: MaxEncodedLen)
	fn create_coin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `4489`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 4489)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}

	/// Storage: MultiCoin CoinMetadata (r:1 w:0)
	/// Proof: MultiCoin CoinMetadata (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	/// Storage: MultiCoin Balances (r:2 w:2)
	/// Proof: MultiCoin Balances (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `6076`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 6076)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage: MultiCoin CoinMetadata (r:1 w:0)
	/// Proof: MultiCoin CoinMetadata (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	/// Storage: MultiCoin MintPermissions (r:1 w:0)
	/// Proof: MultiCoin MintPermissions (max_values: None, max_size: Some(37), added: 2512, mode: MaxEncodedLen)
	/// Storage: MultiCoin TotalSupply (r:1 w:1)
	/// Proof: MultiCoin TotalSupply (max_values: None, max_size: Some(20), added: 2495, mode: MaxEncodedLen)
	/// Storage: MultiCoin Balances (r:1 w:1)
	/// Proof: MultiCoin Balances (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	fn mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `4489`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(21_000_000, 4489)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage: MultiCoin CoinMetadata (r:1 w:0)
	/// Proof: MultiCoin CoinMetadata (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	/// Storage: MultiCoin Balances (r:1 w:1)
	/// Proof: MultiCoin Balances (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: MultiCoin TotalSupply (r:1 w:1)
	/// Proof: MultiCoin TotalSupply (max_values: None, max_size: Some(20), added: 2495, mode: MaxEncodedLen)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `4489`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(17_000_000, 4489)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage: MultiCoin CoinMetadata (r:1 w:1)
	/// Proof: MultiCoin CoinMetadata (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	/// Storage: MultiCoin MintPermissions (r:1 w:1)
	/// Proof: MultiCoin MintPermissions (max_values: None, max_size: Some(37), added: 2512, mode: MaxEncodedLen)
	/// Storage: MultiCoin MintPermissions (r:0 w:1)
	/// Proof: MultiCoin MintPermissions (max_values: None, max_size: Some(37), added: 2512, mode: MaxEncodedLen)
	fn transfer_ownership() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `4489`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 4489)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}

	/// Storage: MultiCoin CoinMetadata (r:1 w:0)
	/// Proof: MultiCoin CoinMetadata (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	/// Storage: MultiCoin MintPermissions (r:0 w:1)
	/// Proof: MultiCoin MintPermissions (max_values: None, max_size: Some(37), added: 2512, mode: MaxEncodedLen)
	fn set_mint_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `4489`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_000_000, 4489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Storage: MultiCoin CoinMetadata (r:1 w:1)
	/// Proof: MultiCoin CoinMetadata (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	fn set_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `4489`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 4489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	fn set_fee_config() -> Weight {
		// Similar to set_metadata: 1 read, 1 write
		Weight::from_parts(11_000_000, 4489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: MultiCoin CoinMetadata (r:1 w:1)
	/// Proof: MultiCoin CoinMetadata (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	/// Storage: MultiCoin SymbolToId (r:1 w:1)
	/// Proof: MultiCoin SymbolToId (max_values: None, max_size: Some(256), added: 2731, mode: MaxEncodedLen)
	/// Storage: MultiCoin NextCoinId (r:1 w:1)
	/// Proof: MultiCoin NextCoinId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: MultiCoin TotalSupply (r:0 w:1)
	/// Proof: MultiCoin TotalSupply (max_values: None, max_size: Some(20), added: 2495, mode: MaxEncodedLen)
	/// Storage: MultiCoin Balances (r:0 w:1)
	/// Proof: MultiCoin Balances (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: MultiCoin MintPermissions (r:0 w:1)
	/// Proof: MultiCoin MintPermissions (max_values: None, max_size: Some(37), added: 2512, mode: MaxEncodedLen)
	fn create_coin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `4489`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 4489)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}

	/// Storage: MultiCoin CoinMetadata (r:1 w:0)
	/// Proof: MultiCoin CoinMetadata (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	/// Storage: MultiCoin Balances (r:2 w:2)
	/// Proof: MultiCoin Balances (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `6076`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 6076)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	/// Storage: MultiCoin MintPermissions (r:1 w:0)
	/// Proof: MultiCoin MintPermissions (max_values: None, max_size: Some(37), added: 2512, mode: MaxEncodedLen)
	/// Storage: MultiCoin TotalSupply (r:1 w:1)
	/// Proof: MultiCoin TotalSupply (max_values: None, max_size: Some(20), added: 2495, mode: MaxEncodedLen)
	/// Storage: MultiCoin Balances (r:1 w:1)
	/// Proof: MultiCoin Balances (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	fn mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `4489`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(21_000_000, 4489)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	/// Storage: MultiCoin Balances (r:1 w:1)
	/// Proof: MultiCoin Balances (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: MultiCoin TotalSupply (r:1 w:1)
	/// Proof: MultiCoin TotalSupply (max_values: None, max_size: Some(20), added: 2495, mode: MaxEncodedLen)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `4489`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(17_000_000, 4489)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	/// Storage: MultiCoin CoinMetadata (r:1 w:1)
	/// Proof: MultiCoin CoinMetadata (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	/// Storage: MultiCoin MintPermissions (r:1 w:1)
	/// Proof: MultiCoin MintPermissions (max_values: None, max_size: Some(37), added: 2512, mode: MaxEncodedLen)
	/// Storage: MultiCoin MintPermissions (r:0 w:1)
	/// Proof: MultiCoin MintPermissions (max_values: None, max_size: Some(37), added: 2512, mode: MaxEncodedLen)
	fn transfer_ownership() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `4489`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 4489)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}

	/// Storage: MultiCoin CoinMetadata (r:1 w:0)
	/// Proof: MultiCoin CoinMetadata (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	/// Storage: MultiCoin MintPermissions (r:0 w:1)
	/// Proof: MultiCoin MintPermissions (max_values: None, max_size: Some(37), added: 2512, mode: MaxEncodedLen)
	fn set_mint_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `4489`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_000_000, 4489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	/// Storage: MultiCoin CoinMetadata (r:1 w:1)
	/// Proof: MultiCoin CoinMetadata (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	fn set_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `4489`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 4489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn set_fee_config() -> Weight {
		// Similar to set_metadata: 1 read, 1 write
		Weight::from_parts(11_000_000, 4489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
